/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author abcde
 */
public class ReadView extends javax.swing.JFrame {

    /**
     * Creates new form ReadView
     */
    public ReadView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sp_images = new javax.swing.JScrollPane();
        pn_images = new javax.swing.JPanel();
        cbo_chapter = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btn_nextChap = new javax.swing.JButton();
        btn_previousChap = new javax.swing.JButton();
        btn_home = new javax.swing.JButton();
        lbl_chapter = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_comicName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_chapterId = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pn_images.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout pn_imagesLayout = new javax.swing.GroupLayout(pn_images);
        pn_images.setLayout(pn_imagesLayout);
        pn_imagesLayout.setHorizontalGroup(
            pn_imagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );
        pn_imagesLayout.setVerticalGroup(
            pn_imagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
        );

        sp_images.setViewportView(pn_images);

        jLabel1.setText("Chapter:");

        btn_nextChap.setText(">>");

        btn_previousChap.setText("<<");

        btn_home.setText("Home");

        lbl_chapter.setForeground(new java.awt.Color(153, 153, 255));

        jLabel2.setText("Comic:");

        lbl_comicName.setForeground(new java.awt.Color(153, 153, 255));

        jLabel3.setText("Id:");

        lbl_chapterId.setForeground(new java.awt.Color(153, 153, 255));

        jLabel4.setText("Chapter:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_home)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbo_chapter, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_nextChap, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_previousChap, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_comicName, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_chapter, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(115, 115, 115)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_chapterId, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(sp_images, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btn_home)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cbo_chapter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btn_nextChap)
                        .addGap(18, 18, 18)
                        .addComponent(btn_previousChap))
                    .addComponent(lbl_comicName, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lbl_chapter, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(lbl_chapterId, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sp_images, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReadView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReadView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReadView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReadView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReadView().setVisible(true);
            }
        });
    }

    public JButton getBtn_home() {
        return btn_home;
    }

    public void setBtn_home(JButton btn_home) {
        this.btn_home = btn_home;
    }

    public JButton getBtn_nextChap() {
        return btn_nextChap;
    }

    public void setBtn_nextChap(JButton btn_nextChap) {
        this.btn_nextChap = btn_nextChap;
    }

    public JButton getBtn_previousChap() {
        return btn_previousChap;
    }

    public void setBtn_previousChap(JButton btn_previousChap) {
        this.btn_previousChap = btn_previousChap;
    }

    public JComboBox<String> getCbo_chapter() {
        return cbo_chapter;
    }

    public void setCbo_chapter(JComboBox<String> cbo_chapter) {
        this.cbo_chapter = cbo_chapter;
    }

    public JLabel getLbl_chapter() {
        return lbl_chapter;
    }

    public void setLbl_chapter(JLabel lbl_chapter) {
        this.lbl_chapter = lbl_chapter;
    }

    public JLabel getLbl_chaptetId() {
        return lbl_chapterId;
    }

    public void setLbl_chaptetId(JLabel lbl_chaptetId) {
        this.lbl_chapterId = lbl_chaptetId;
    }

    public JLabel getLbl_comicName() {
        return lbl_comicName;
    }

    public void setLbl_comicName(JLabel lbl_comicName) {
        this.lbl_comicName = lbl_comicName;
    }

    public JPanel getPn_images() {
        return pn_images;
    }

    public void setPn_images(JPanel pn_images) {
        this.pn_images = pn_images;
    }

    public JScrollPane getSp_images() {
        return sp_images;
    }

    public void setSp_images(JScrollPane sp_images) {
        this.sp_images = sp_images;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_nextChap;
    private javax.swing.JButton btn_previousChap;
    private javax.swing.JComboBox<String> cbo_chapter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbl_chapter;
    private javax.swing.JLabel lbl_chapterId;
    private javax.swing.JLabel lbl_comicName;
    private javax.swing.JPanel pn_images;
    private javax.swing.JScrollPane sp_images;
    // End of variables declaration//GEN-END:variables
}
